config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'post_images#index'
  resources :post_images, only: [:new, :create, :index, :show, :destroy, :edit, :update] do
  resources :post_comments, only: [:create, :destroy]
  resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
  get '/search', to: 'searches#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image

  validates :comment, presence: true
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tags, dependent: :destroy

  validates :image, presence: true
  validates :shop_name, presence: true
  validates :caption, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image, destroy: false

  validates :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: @post_image.id)
    favorite.save
  end

  def destroy
    @post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: @post_image.id)
    favorite.destroy
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
def create
    @post_image = PostImage.find(params[:post_image_id])
    @comment = current_user.post_comments.new(post_comment_params)
    @comment.post_image_id = @post_image.id
    if @comment.save
    redirect_to post_image_path(@post_image)
    flash[:notice] = "コメントしました！"
    else
    render("post_images/index")
    end

end

def destroy
   postcomment = PostComment.find_by(id: params[:id])
   postcomment.destroy
   redirect_to post_image_path(params[:post_image_id])
   flash[:notice] = "削除しました！"
end

private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end

end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  def index
    if params[:post_image].present?
      if params[:post_image].empty?
        @post_images = PostImage.page(params[:page]).per(5)
      else
        @post_images = PostImage.where('shop_name LIKE(?)', "%#{params[:post_image][:keyword]}%")
      end
    else
      @post_images = PostImage.page(params[:page]).per(5)
    end
  end

  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end

  def new
    @post_image = PostImage.new
  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.score = Language.get_data(post_image_params[:caption])
    if @post_image.save
    tags = Vision.get_image_data(@post_image)
    tags.each do |tag|
      @post_image.tags.create(name: tag)
    end
      redirect_to root_path
      flash[:notice] = "投稿しました！"
    else
      render("post_images/new")
    end
  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to root_path
    flash[:notice] = "削除しました！"
  end

  def update
   @post_image = PostImage.find(params[:id])
   if @post_image.update(post_image_params)
    flash[:notice] = "編集しました！"
   redirect_to post_image_path(@post_image.id)
   else
    render("post_images/edit")
   end
  end


  def edit
   @post_image = PostImage.find(params[:id])
  end

  private

  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption, :address)
  end

end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

  def search
    # viewのform_tagにて
    # 選択したmodelの値を@modelに代入。
    @model = params["model"]
    # 選択した検索方法の値を@methodに代入。
    @method = params["method"]
    # 検索ワードを@contentに代入。
    @content = params["content"]
    # @model, @content, @methodを代入した、
    # search_forを@recordsに代入。
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)

    # 選択したモデルがuserだったら
    if model == 'user'
      # 選択した検索方法がが完全一致だったら
      if method == 'perfect'
      return User.where(name: content)
      # 選択した検索方法がが部分一致だったら
      elsif method == 'partial'
      return User.where('name LIKE ?', '%'+content+'%')
      # 選択した検索方法がが前方一致だったら
      elsif method == 'forward_match'
      return User.where('name LIKE ?', content+'%')
      # 選択した検索方法がが後方一致だったら
      elsif method == 'backward_match'
      return User.where('name LIKE ?', '%'+content)
      end
    # 選択したモデルがpost_imageだったら
    elsif model == 'post_image'
      # 選択した検索方法がが完全一致だったら
      if method == 'perfect'
      return PostImage.where(shop_name: content)
      # 選択した検索方法がが部分一致だったら
      elsif method == 'partial'
      return PostImage.where('shop_name LIKE ?', '%'+content+'%')
      # 選択した検索方法がが前方一致だったら
      elsif method == 'forward_match'
      return PostImage.where('shop_name LIKE ?', content+'%')
      # 選択した検索方法がが後方一致だったら
      elsif method == 'backward_match'
      return PostImage.where('shop_name LIKE ?', '%'+content)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :ensure_correct_user, only: [:update, :edit]

  def index
    if params[:user].present?
      if params[:user].empty?
        @users = User.page(params[:page]).per(12)
      else
        @users = User.where('name LIKE(?)', "%#{params[:user][:keyword]}%")
      end
    else
      @users = User.page(params[:page]).per(12)
    end
  end

  def show
   @user = User.find(params[:id])
   @post_images = @user.post_images.page
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
      flash[:notice] = "プロフィールを更新しました！"
    else
      render("users/edit")
    end
  end

  def edit
    @user = User.find(params[:id])
  end


  print
  def user_params
    params.require(:user).permit(:name, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>

<% if post_image.favorited_by?(current_user) %>
  <%= link_to post_image_favorites_path(post_image), method: :delete, remote: true do %>
  ♥<%= post_image.favorites.count %>
  <% end %>
  <% else %>
  <%= link_to post_image_favorites_path(post_image), method: :post, remote: true do %>
  ♡<%= post_image.favorites.count %>
  <% end %>
  <% end %>
 <% end %>

app/views/favorites/create.js.erb
$('#favorite_buttons_<%= @post_image.id %>').html("<%= j(render "favorites/favorite", post_image: @post_image) %>")

app/views/favorites/destroy.js.erb
$('#favorite_buttons_<%= @post_image.id %>').html("<%= j(render "favorites/favorite", post_image: @post_image) %>");

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %>が出ています(記入漏れ)</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DodeTown</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <div style="background-color: white;">
  <body class="d-flex flex-column vh-100">
    <div class="footerFixed">
      <header class="shadow-sm">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">
            <a class="navbar-brand p-3" href="/">DodeTown</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav ml-auto">
                <div class="d-flex justify-content-center">
                    <%= form_tag(search_path, method: :get) do %>
                    <%= text_field_tag 'content' %>
                    <%= select_tag 'model', options_for_select({ "投稿者" => "user", "ショップ名" => "post_image" }) %>
                    <%= select_tag 'method', options_for_select({ "完全一致" => "perfect", "部分一致" => "partial", "前方一致" => "forward_match", "後方一致" => "backward_match" }) %>
                    <%= submit_tag '検索' %>
                    <% end %>
                </div>
                <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "fa fa-times-circle nav-link text-dark" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to '投稿フォーム', new_post_image_path, class: "fa fa-camera nav-link text-dark" %>
                  </li>
                  <li class="nav-item">
                    <%= link_to '投稿者一覧', users_path, class: 'fas fa-users nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to 'マイページ',edit_user_path(current_user), class: "fa fa-address-book nav-link text-dark" %>
                  </li>
                <% else %>
                  <li class="nav-item">
                    <%= link_to "新規登録", new_user_registration_path, class: 'fa fa-user-plus nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to "ログイン", new_user_session_path, class: 'fa fa-key nav-link text-dark' %>
                  </li>
                  <li class="nav-item">
                    <%= link_to '投稿者一覧', users_path, class: 'fas fa-users nav-link text-dark' %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer>
      <p>青森のめえもん食いにいぐべ</p>
    </footer>
    </div>
    </body>
  </div>
</html>

app/views/post_comments/_form.html.erb
<% if user_signed_in? %>

<%= form_with(model:[post_image, post_comment]) do |f| %>
<%= f.text_area :comment, placeholder: "コメントをここに" %>
<%= f.submit "送信する" %>
<% end %>
<% end %>

app/views/post_comments/_post_comment.html.erb
<table class='table'>
  <% post_image.post_comments.each do |post_comment| %>
  <tr>
    <td><%= post_image.user.name %></td>
    <td><%= post_comment.comment %></td>
        <% if post_comment.user == current_user %>
    <td><%= link_to 'Destroy', post_image_post_comment_path(post_comment.post_image, post_comment), method: :delete, remote: true, class: "btn btn-sm btn-danger destroy_book_#{post_image.id}"%></td>
        <% end %>
  </tr>
  <% end %>
</table>

app/views/post_images/_index.html.erb
<div class="background">

<% if flash[:notice] %>
  <p id="notice">
    <%= flash[:notice] %>
  </p>
<% end %>

<svg class="p-top-kv__ttl-svg">
  <div class="text-center">
  <h1>青森のめえ〜店を語り合うサイト</h1>
  </div>
</svg>

<div class="card-list-container py-5">

  <% if post_images.present? %>
  <% post_images.each do |post_image| %>
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= link_to post_image_path(post_image.id) do %>
      <%= attachment_image_tag post_image, :image, class:"card-img-top"; %>
    <% end %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <td><%= link_to user_path(post_image.user) do %>
          <%= attachment_image_tag post_image.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", class:"mt-3 rounded-circle"; %>
          <% end %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to(post_image_path(post_image.id), class:"text-dark") do %>
              <strong><i class="far fa-flag"></i><span> <%= post_image.shop_name %></span></strong>
            <% end %>
          </p>
          <% post_image.tags.each do |tag| %>
          <span class="label"><%= tag.name %></span>
          <% end %>
          <p class="card-text">住所：<%= post_image.address %></p>
          <p class="card-text">説明：<%= post_image.caption %></p>
          <span class="sentiment-score">説明文の感情分析スコア<%= post_image.score %></span>
          <span><i class="fas fa-user"></i> By <%= post_image.user.name %></span>
          <div id="favorite_buttons_<%= post_image.id %>">
          <%= render "favorites/favorite", post_image: post_image, current_user: current_user %>
          </div>
          <span><%= link_to "#{post_image.post_comments.count} コメント", post_image_path(post_image.id), class:"text-dark" %></span>
        </div>
      </div>
    </div>
  </div>
  <% end %>
  <% else %>
  <div class="seaches_background">
    <pclass="mx-auto white">検索に合致するものはありません</p>
  </div>
  <% end %>

</div>
</div>

<script>
document.addEventListener('turbolinks:load',function(){
$('.search__form__input').on('keyup', function(e){
      Rails.fire($(".search__form")[0], "submit");
  });
});

</script>

app/views/post_images/edit.html.erb
<h1>編集ページ</h1>
<%= render 'layouts/errors', obj: @post_image %>

<%= form_with model:@post_image, local:true do |f| %>
<h4>画像</h4>
<%= f.attachment_field :image %>
<h4>ショップ名</h4>
<%= f.text_field :shop_name %>
<h4>住所</h4>
<%= f.text_field :address %>
<h4>説明</h4>
<%= f.text_area :caption %>
<%= f.submit '保存' %>
<% end %>

app/views/post_images/index.html.erb
<div class="row mx-auto whiteback">
    <div class="search mx-auto">
      <%= form_with model: PostImage.new, method: :get, class: "search__form" do |f| %>
        <%= f.text_field :keyword, required: true, class: "search__form__input searchTerm" %>
        <button type="submit" class="searchButton">
        <i class="fa fa-search"></i>
        </button>
      <% end %>
      <%= paginate @post_images %>
    </div>
  </div>
  <div id="index">
   <%= render 'post_images/index', post_images: @post_images%>
  </div>

app/views/post_images/index.js.erb
$("#index").html("<%= escape_javascript(render partial: "post_images/index", locals: {post_images: @post_images}) %>");

app/views/post_images/new.html.erb
<div class="new_background">

<%= render 'layouts/errors', obj: @post_image %>
<h1>画像投稿フォーム</h1>
<%= form_with model: @post_image, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <h4>ショップ名</h4>
  <%= f.text_field :shop_name %>
  <h4>住所</h4>
  <%= f.text_field :address %>
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>
</div>

app/views/post_images/show.html.erb
<!--<div style="background-color: aqua;">-->

<% if flash[:notice] %>
  <p id="notice">
    <%= flash[:notice] %>
  </p>
<% end %>

<div>
  <%= attachment_image_tag @post_image, :image %>
  <p>店名：<%= @post_image.shop_name %></p>
  <% @post_image.tags.each do |tag| %>
  <span class="label"><%= tag.name %></span>
  <% end %>
  <p>住所: <%= @post_image.address %></p>

<div id="map"></div>

<style>
#map{
  height: 150px;
  width:270px;
}
</style>

<script type="text/javascript">
    function initMap() {

        var test ={lat: <%= @post_image.latitude %>, lng: <%= @post_image.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: test
        });
        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        var contentString = '住所：<%= @post_image.address %>';
        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

        var marker = new google.maps.Marker({
            position:test,
            map: map,
            title: contentString
        });

        marker.addListener('click', function() {
            infowindow.open(map, marker);
        });
    }
</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap">
</script>



  <p>説明：<%= @post_image.caption %></p>
  <p class="sentiment-score">説明文の感情分析スコア[<%= @post_image.score %>]</p>
  <p>ユーザーネーム：<%= @post_image.user.name %></p>
  <p>投稿日時：<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <div id="favorite_buttons_<%= @post_image.id %>">
  <%= render "favorites/favorite", post_image: @post_image %>
  </div>
  <td>コメント数：<%= @post_image.post_comments.count %></td>
  <div id="comments_area">
   <%= render 'post_comments/post_comment', post_image: @post_image %>
  </div>
  <div class="new-comment">
   <%= render 'post_comments/form', post_image: @post_image, post_comment: @post_comment %>
  </div>
  <% if @post_image.user == current_user %>
    <%= link_to "削除", post_image_path(@post_image), method: :delete %>
    |
    <%= link_to "編集", edit_post_image_path(@post_image) %>
  <% end %>
<!--</div>-->

app/views/searches/search.html.erb
<div class="seach_background">

<% if @model == 'user' %>
  <h2 class="search">投稿者の検索結果 "<%= @content %>"</h2>
  <%= render 'users/index', users: @records %>
<% else @model == 'post_image' %>
  <h2 class="search">ショップ名の検索結果 "<%= @content %>"</h2>
    <%= render 'post_images/index', post_images: @records %>
<% end %>
</div>

app/views/users/_index.html.erb
<div class="user_background">
<div class="row result">
  <div class="col-11 mx-auto">
    <div class="d-flex align-content-start flex-wrap mt-4">
      <% if users.present? %>
      <% users.each do |user| %>
      <div class="mx-5 my-4 out-line">
        <%= link_to user_path(user),class: "user_#{user.id}" do %>
          <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "180x180" %><br>
        <% end %>
        <div class="text-center"><%= user.name %></div>
      </div>
      <% end %>
      <% else %>
        <pclass="mx-auto white">検索に合致するものはありません</p>
      <% end %>
    </div>
  </div>
</div>
</div>

<script>
document.addEventListener('turbolinks:load',function(){
$('.search__form__input').on('keyup', function(e){
      Rails.fire($(".search__form")[0], "submit");
  });
});

</script>

app/views/users/edit.html.erb
<div class="edit_background">
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto mt-100">
    <h2>プロフィール編集</h2>
    <%= form_with model:@user, local:true do |f| %>
    <%= render 'layouts/errors', obj: @user %>

    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
    </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
     </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>
</div>

app/views/users/index.html.erb
<h1 class="whiteback">投稿者一覧</h1>

<!--<#%= render 'index', users: @users %>-->

<div class="row mx-auto whiteback">
    <div class="search mx-auto">
      <%= form_with model: User.new, method: :get, class: "search__form" do |f| %>
        <%= f.text_field :keyword, required: true, class: "search__form__input searchTerm" %>
        <button type="submit" class="searchButton">
        <i class="fa fa-search"></i>
        </button>
      <% end %>
    </div>
</div>
  <div id="index">
    <%= render "users/index", users: @users %>
  </div>

  <%= paginate @users %>


<!--<script>-->
<!--document.addEventListener('turbolinks:load',function(){-->
<!--$('.search__form__input').on('keyup', function(e){-->
<!--      Rails.fire($(".search__form")[0], "submit");-->
<!--  });-->
<!--});-->

<!--</script>-->

app/views/users/index.js.erb
$("#index").html("<%= escape_javascript(render partial: "users/index", locals: {users: @users}) %>");

app/views/users/show.html.erb
<%= render 'post_images/index', post_images: @post_images%>